### ISSUE TITLE
cannot activate plugin

### ISSUE THREAD

**Issue by polifinario** [MikhailRoot/woo-webinarjam#1]
I downloaded the plugin but I cannot activate it. 

Error:
Parse error: syntax error, unexpected '[' in /WWW/A/.5c2/v/vanvug12/htdocs/2013/wp-content/plugins/woo-webinarjam-master/woo-webinarjam.php on line 80

**Comment by MikhailRoot** [comment]
Hi! sorry for this problem. I've written it in PHP 7 environment. The root of this issue is short [] and full old array() notation. I've just updated code to support PHP 5.3. Now it will work fine. Just download latest source now. Also I'd like to advice you to change PHP version to 5.6 at least, because as I see you are using 5.3 and its a bit outdated.

**Comment by polifinario** [comment]
Thank you very much! I downloaded the update and now I managed to activate the plugin. But on the settings page I only see an empty screen.

**Comment by MikhailRoot** [comment]
Thank you for feed back. It was same problem with short array syntax supported only since php 5.4
I've fixed it to make it backward compatible with 5.3.

**Comment by polifinario** [comment]
Thank you Mikhail! It works smoothly now!

**Comment by polifinario** [comment]
Goodmorning Mikhail,
I have one more problem. I tested the updated version with my own emailadress and a 100% discount. Then it all worked fine. The people that register for my webinar however can successfully make a payment but then I get the message "Error while registering Paid user to webinar XYZ". Could this possibly also be a PHP version issue?

Cheers,
Martijn

**Comment by MikhailRoot** [comment]
I'll explain what it does after successful payment - it get's you'r client's data: first and last name, email and makes a request to webinarjam api server to  register client and get access links for him, to send this info to your client and you as admin. this is done through wp_remote_post function which depends on curl module in PHP. So check if curl module is enabled and working. Also I strongly advice you to upgrade PHP version at least to 5.6.

**Comment by polifinario** [comment]
According to system status the cURL version is 7.38.0, OpenSSL/1.0.1t. I assume that it is enabled and working, otherwise it would not show this??
But still the subscriptions do not get through the API to WebinarJam :(
The PHP version is upgraded to 5.6.

**Comment by MikhailRoot** [comment]
I've updated code to use WP_Errors, so on error while registration you'll recieve email with error description. it'll help us to debug and find out your source of problem.
