### ISSUE TITLE
Conflicts with Woocommerce Downloadable Files

### ISSUE THREAD

**Issue by akwinter** [MikhailRoot/woo-webinarjam#2]
Thanks for this plugin - exactly what I was looking for! 

I noticed after experimenting with your plugin that the downloadable files section disappears for simple products (see before / after screenshots).

Also, it seems email templates in Settings are unnecessary since Webinarjam already automatically sends their own email templates after registration so I hid the snippet under "let's send prepared mail to user"

Thanks!
![before-webinarjam](https://user-images.githubusercontent.com/48691745/54552956-3fb4d280-497f-11e9-97b7-065f192253fb.png)
![after-webinarjam](https://user-images.githubusercontent.com/48691745/54553067-696df980-497f-11e9-950e-bae287e75f3c.png)

**Comment by MikhailRoot** [comment]
@akwinter thank you for catch on this! now fixed. General tab isn't hidden anymore on other products when plugin is activated.
Also i've added checkbox to enable\disable sending custom email notification to client after registering to webinar.
Please confirm if it's fixed on your end after you'll update a plugin, get most recent version from master branch.
